import pytest

import find_codon as fc

test_seq = 'ATGGAGAACAACGAAGCCCCCTCCCCCTCGGGATCCAACAACAACGAGAACAACAATGCAGCCCAGAAGA\
AGCTGCAGCAGACCCAAGCCAAGGTGGACGAGGTGGTCGGGATTATGCGTGTGAACGTGGAGAAGGTCCT\
GGAGCGGGACCAGAAGCTATCGGAACTGGGCGAGCGTGCGGATCAGCTGGAGCAGGGAGCATCCCAGTTC\
GAGCAGCAGGCCGGCAAGCTGAAGCGCAAGCAATGGTGGGCCAACATGAAGATGATGATCATTCTGGGCG\
TGATAGCCGTTGTGCTGCTCATCATCGTTCTGGTGTCGCTTTTCAATTGA'

def test_find_codon_lesson6():
    assert fc.find_codon_lesson6('ATG', test_seq) == 0
    assert fc.find_codon_lesson6('TGG', test_seq) == 1
    assert fc.find_codon_lesson6('AAT', test_seq ) == 54
    assert fc.find_codon_lesson6('')


    return None
